esphome:
  name: heartview-hr

esp32:
  board: seeed_xiao_esp32c6
  framework:
    type: esp-idf

logger:
  level: DEBUG
  logs:
    seeed_mr60bha2: NONE
    uart.idf: INFO

web_server:
  port: 80

api:
  encryption:
    key: "${API_KEY}"

ota:
  - platform: esphome

wifi:
  ssid: "Josnow"
  password: "fuckjohnsnow"
  fast_connect: true
  output_power: 8.5
  ap:
    ssid: "HeartView-Fallback"
    password: "heartview1234"

captive_portal:

uart:
  id: uart_bus
  tx_pin: GPIO16
  rx_pin: GPIO17
  baud_rate: 115200

seeed_mr60bha2:
  uart_id: uart_bus

binary_sensor:
  - platform: seeed_mr60bha2
    has_target:
      name: "Presence Detected"

sensor:
  - platform: seeed_mr60bha2
    heart_rate:
      name: "Current Heart Rate"
      filters:
        - sliding_window_moving_average:
            window_size: 10
            send_every: 5
        - filter_out: 0
    breath_rate:
      name: "Current Breath Rate"
      filters:
        - sliding_window_moving_average:
            window_size: 10
            send_every: 5
        - filter_out: 0